--TẠO DATABASE
USE master
GO
CREATE DATABASE QUANLYTRACNGHIEM 
ON PRIMARY (
NAME = 'QUANLYTRACNGHIEM_DATA',
FILENAME = 'E:\HQTCSDL\QUANLYTRACNGHIEM_DATA.mdf',
SIZE = 50MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 5MB
)
LOG ON (
NAME = 'QUANLYTRACNGHIEM_LOG',
FILENAME = 'E:\HQTCSDL\QUANLYTRACNGHIEM_LOG.ldf',
SIZE = 20MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 5MB
)
COLLATE Vietnamese_CI_AS;
GO
--TẠO TABLE 
USE QUANLYTRACNGHIEM
GO
CREATE TABLE HOCVIEN (
MAHV INT IDENTITY PRIMARY KEY,
HOHV NVARCHAR(20) NOT NULL,
TENHV NVARCHAR(20) NOT NULL,
DIACHI NVARCHAR(100) NULL,
GIOITINH NVARCHAR(3) NOT NULL CHECK (GIOITINH IN (N'Nam',N'Nữ')),
SDT NUMERIC(12,0) NOT NULL CHECK (SDT > 0 AND LEN(SDT)<12),
MATKHAU NVARCHAR(16) NOT NULL CHECK (LEN(MATKHAU) > 5),
MALH INT NULL
)
GO 
CREATE TABLE LOPHOC (
MALH INT IDENTITY PRIMARY KEY,
TENLH NVARCHAR(20) UNIQUE NOT NULL
)
GO
CREATE TABLE MONHOC (
MAMH INT IDENTITY PRIMARY KEY,
TENMH NVARCHAR(20) UNIQUE NOT NULL
)
GO
CREATE TABLE CHUONG (
MACHUONG INT IDENTITY PRIMARY KEY,
TENCHUONG NVARCHAR(20) NOT NULL,
MAMH INT NULL
)
GO
CREATE TABLE CAUHOI (
MACH INT IDENTITY PRIMARY KEY,
NOIDUNG TEXT NOT NULL,
DAPANA TEXT NOT NULL,
DAPANB TEXT NOT NULL,
DAPANC TEXT NOT NULL,
DAPAND TEXT NOT NULL,
DAPANDUNG VARCHAR(1) NOT NULL,
MACHUONG INT NULL
)
GO
CREATE TABLE DETHI (
MADT INT IDENTITY PRIMARY KEY,
NGAYTHI DATE NOT NULL,
MAMH INT NULL
)
GO
CREATE TABLE DANHSACHMH (
MALH INT NOT NULL,
MAMH INT NOT NULL,
CONSTRAINT PK_DSMH PRIMARY KEY (MALH,MAMH)
)
GO
CREATE TABLE CHITIETDETHI(
MACH INT NOT NULL,
MADT INT NOT NULL,
SOTT INT NOT NULL,
CONSTRAINT PK_CTDT PRIMARY KEY (MACH, MADT, SOTT)
)
GO
CREATE TABLE CHITIETBAILAM (
MAHV INT NOT NULL,
MADT INT NOT NULL,
SOTT INT NOT NULL,
CAUTL VARCHAR(1) NULL, 
CONSTRAINT PK_CTBL PRIMARY KEY (MAHV, MADT, SOTT),
)
GO
--THÊM CONSTRAINT 
ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HVLH FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH)
GO
ALTER TABLE CHUONG ADD CONSTRAINT FK_CMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
GO
ALTER TABLE CAUHOI ADD CONSTRAINT FK_CHC FOREIGN KEY (MACHUONG) REFERENCES CHUONG(MACHUONG)
GO
ALTER TABLE DANHSACHMH ADD CONSTRAINT FK_DSMH_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
GO
ALTER TABLE DANHSACHMH ADD CONSTRAINT FK_DSMH_LH FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH)
GO
ALTER TABLE CHITIETDETHI ADD CONSTRAINT FK_CTDT_DT FOREIGN KEY (MADT) REFERENCES DETHI(MADT)
GO
ALTER TABLE CHITIETDETHI ADD CONSTRAINT FK_CTDT_CH FOREIGN KEY (MACH) REFERENCES CAUHOI(MACH)
GO
ALTER TABLE CHITIETDETHI ADD CONSTRAINT CHECK_RANGE CHECK (SOTT >0 AND SOTT <41)
GO
ALTER TABLE CHITIETBAILAM ADD CONSTRAINT FK_CTBL_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)
GO
ALTER TABLE CHITIETBAILAM ADD CONSTRAINT FK_CTBL_DT FOREIGN KEY (MADT) REFERENCES DETHI(MADT)
GO
ALTER TABLE CHITIETBAILAM ADD CONSTRAINT CHECK_RANGE_BL CHECK (SOTT >0 AND SOTT <41)
GO

